# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS-latest'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

# The `certSecureFile` and `provProfileSecureFile` files are uploaded to the Azure Pipelines secure files library where they are encrypted.
# The `P12Password` variable is set in the Azure Pipelines pipeline editor and marked 'secret' to be encrypted.
steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'fni.p12'
    certPwd: ''

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'fniinvitationa_PROD.mobileprovision'